print('Olá seja Bem vindo!')
n=input('Qual seu nome? ')
print('Legal',n)
print(n, 'eu vou te fazer algumas perguntas;')
input('Posso? ')
print('vou continuar então assim mesmo...')
d=input('Qual o dia do seu nascimeno? ')
m=input('E o mês? ')
a=input('No ano de? ')
print('Seu nome é',n,'você nasceu em',d,'do mês de',m,'no ano de',a,'?')
input('Correto? ')
print('Então',n,'a notícia não é muito boa você é virgem diz meu google...')
