x=input('Digite algo: ')
print('Esse digito é do tipo:',(type(x)))
print('Ele é uma letra do alfabeto?',x.isalpha())
print('Ele está maiúsculo?',x.isupper())
print('Ele está minúsculo?',x.islower())
print('Ele é uma frase com letra maiúscula no início?',x.istitle())
print('Ele é alfanumérico?',x.isalnum())
print('Ele é um número?',x.isnumeric())
print('Ele é um digito?',x.isdigit())
print('Ele é um decimal?',x.isdecimal())
print('Ele é espaço?',x.isspace())
print('Ele pode ser impresso?',x.isprintable())
print('Ele é um ascii?',x.isascii())
print('É possivel escrever um código com ele?',x.isidentifier())
print('Analize concluída com sucesso.')
